### PR TITLE
newspage: 3d code review

### PR DESCRIPTION
**Pull request by ricardovaltierra**
There where solved several issues for this updated pull request:

* z-index order on nav
* 'display: none' of nav elements for mobile and tablet
* colors tooken away from containers
* github README.md file update
* pull request formated
* most issues made by last code review solved

### CODE REVIEW

**Comment by izaiasneto4** [comment]
### Hello @ricardovaltierra. Please keep in mind that you need to correct the following errors with your repository and submit again in order for it to be reviewed. :arrow_down: 

- [x] Add a meaningful title and a short summary for your Pull Request

- [x] Make sure that you have a descriptive README file

If you need a reference on how to do these tasks, please take a look at [this lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

####  Please, when finished with these changes submit your project again for a new review :smiley:

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi @ricardo,   
You have done a good on this one. 
Here are a few issues we have to address to get this project approved.
* [x] let us add the remaining parts of the page. Your project currently ends at the featured slideshow. refer to [newsweek](newsweek.com)🙂.
> take note of how each of this element behaves at different breakpoints
* [x] Your logo image is not loading as it should🙂.
you can use the Newsweek logo with a class of ```.img-fluid``` and make sure the path specified is right. 
* [x] The hamburger in the navigation is not displaying as required🙂
You can use font awesome's ```fa fa-hamburger``` for this
* [x] The subscribe link is also not looking good🙂.
kindly style it,  you can even add ```.btn btn-light``` take inspiration from the [original page](newsweek.com)
this is how navigation looks currently ⬇️

Screenshot from 2019-12-03 12-12-00

Screenshot from 2019-12-03 12-37-43
Screenshot from 2019-12-03 12-38-03
* [ ] Let us also take care of this overlaps in the picture below⬇️.
Screenshot from 2019-12-03 12-12-00
compare your project with the original, take note of the behavior and position of the ```sign up button``` newsletter title is also not showing clearly
> 🤔 You have quite a number of images in your page but I have not seen a single use of bootstrap class ```.img-fluid``` remember the main focus of this project is to use bootstrap classes as much as possible which you have but not with respect to ```.img-fluid```

## [optional]🙂
The html validator is returning quite a number of warnings. You may also address them.

# That is it, do these changes and submit the project for review🙂.
Happy coding🙂
ADDO BOAKYE FORISON

**Comment by ricardovaltierra** [comment]
Modification made:
* README.md update (page uploaded to personal server [Live version](https://mvnewsweek.000webhostapp.com/)) <- You can review it directly from here🙂
* Remaining parts of the page added (U.S., World, Business, Tech & Science, Culture, Sports)
* HTML validation warnings solved
* Newsweek logo displaying propperly (online on personal server)
* Hamburger button displaying propperly
* Suscribe link displaying propperly

Thanks for recommendations

**Review by mosesogwo — APPROVED** [review]
## Hi @ricardovaltierra ,

### :clap: Good job. You have done well in implementing the requested changes.

### You may now go ahead and merge to master.

### Status: Approved! :+1: 

## Happy coding!

**Comment by ricardovaltierra** [comment]
Thanks 🙂

**Pull request merged**
